#!/bin/bash

#PARICAL
##########################################################################################
hem='L R'
masks='RS-group-mask-50'
cd /Users/jflanner/Documents/RESTING/group_level/
for h in ${hem} ;
do
	for mask in ${masks} ;
	do
		3dttest++ -prefix p_group-sm8-dinsula_${h}-connect+tlrc \
			-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
			-clustsim \
			-setA \
					193-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					203-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					206-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					211-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					212-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
				  216-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					217-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					218-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					225-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					229-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					237-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					238-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					240-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					242-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					244-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					247-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					248-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					250-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					253-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					254-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					257-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					259-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					263-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					268-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					273-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					280-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					282-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					285-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					287-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
				  289-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					290-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					291-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					293-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					294-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					295-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					296-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					297-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					299-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					300-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					301-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					302-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					306-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					307-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					309-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					310-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					311-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					313-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					315-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					316-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					317-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					319-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					321-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					323-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					324-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					326-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					328-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					331-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					332-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					336-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					337-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					339-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					341-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					343-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					344-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					345-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					346-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					348-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					350-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					351-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					352-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					354-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					357-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					358-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					360-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					363-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					365-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					366-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					373-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					375-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					380-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					383-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					389-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					392-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					397-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					398-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					399-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					401-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					402-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					403-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					404-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					405-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					407-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					410-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
				-resid p_group-dinsula_${h}-connect-resid.nii

			3dttest++ -prefix p_group-pinsula_${h}-connect+tlrc \
						-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
						-clustsim \
						-setA \
								193-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								203-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								206-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								211-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								212-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								216-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								217-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								218-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								225-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								229-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								237-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								238-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								240-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								242-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								244-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								247-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								248-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								250-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								253-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								254-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								257-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								259-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								263-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								268-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								273-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								280-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								282-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								285-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								287-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								289-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								290-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								291-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								293-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								294-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								295-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								296-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								297-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								299-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								300-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								301-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								302-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								306-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								307-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								309-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								310-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								311-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								313-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								315-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								316-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								317-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								319-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								321-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								323-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								324-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								326-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								328-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								331-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								332-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								336-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								337-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								339-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								341-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								343-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								344-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								345-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								346-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								348-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								350-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								351-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								352-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								354-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								357-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								358-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								360-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								363-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								365-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								366-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								373-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								375-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								380-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								383-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								389-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								392-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								397-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								398-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								399-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								401-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								402-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								403-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								404-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								405-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								407-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
								410-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
							-resid p_group-pinsula_${h}-connect-resid.nii

								3dttest++ -prefix p_group-vinsula_${h}-connect+tlrc \
									-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
									-clustsim \
									-setA \
											193-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											203-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											206-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											211-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											212-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											216-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											217-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											218-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											225-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											229-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											237-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											238-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											240-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											242-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											244-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											247-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											248-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											250-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											253-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											254-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											257-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											259-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											263-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											268-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											273-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											280-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											282-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											285-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											287-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											289-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											290-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											291-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											293-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											294-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											295-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											296-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											297-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											299-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											300-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											301-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											302-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											306-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											307-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											309-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											310-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											311-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											313-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											315-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											316-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											317-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											319-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											321-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											323-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											324-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											326-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											328-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											331-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											332-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											336-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											337-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											339-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											341-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											343-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											344-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											345-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											346-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											348-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											350-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											351-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											352-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											354-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											357-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											358-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											360-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											363-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											365-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											366-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											373-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											375-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											380-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											383-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											389-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											392-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											397-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											398-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											399-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											401-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											402-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											403-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											404-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											405-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											407-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
											410-sm8-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
										-resid p_group-vinsula_${h}-connect-resid.nii
		done
done

echo "END Ttest"
