#!/bin/bash

#PARICAL
##########################################################################################
hem='L R'
masks='RS-group-mask-50'
cd /Users/jflanner/Documents/RESTING/group_level/
for h in ${hem} ;
do
	for mask in ${masks} ;
	do
		3dttest++ -prefix d_vs_p-${h}-connect+tlrc \
			-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
			-paired \
			-setA \
					193-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					203-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					206-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					211-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					212-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
				  216-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					217-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					218-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					225-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					229-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					237-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					238-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					240-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					242-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					244-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					247-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					248-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					250-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					253-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					254-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					257-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					259-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					263-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					268-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					273-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					280-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					282-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					285-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					287-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
				  289-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					290-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					291-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					293-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					294-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					295-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					296-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					297-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					299-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					300-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					301-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					302-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					306-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					307-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					309-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					310-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					311-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					313-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					315-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					316-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					317-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					319-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					321-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					323-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					324-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					326-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					328-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					331-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					332-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					336-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					337-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					339-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					341-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					343-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					344-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					345-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					346-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					348-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					350-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					351-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					352-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					354-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					357-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					358-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					360-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					363-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					365-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					366-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					373-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					375-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					380-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					383-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					389-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					392-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					397-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					398-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					399-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					401-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					402-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					403-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					404-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					405-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					407-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
					410-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
			-setB \
					193-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					203-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					206-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					211-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					212-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					216-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					217-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					218-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					225-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					229-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					237-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					238-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					240-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					242-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					244-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					247-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					248-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					250-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					253-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					254-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					257-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					259-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					263-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					268-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					273-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					280-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					282-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					285-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					287-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					289-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					290-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					291-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					293-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					294-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					295-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					296-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					297-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					299-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					300-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					301-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					302-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					306-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					307-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					309-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					310-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					311-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					313-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					315-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					316-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					317-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					319-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					321-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					323-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					324-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					326-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					328-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					331-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					332-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					336-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					337-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					339-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					341-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					343-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					344-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					345-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					346-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					348-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					350-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					351-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					352-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					354-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					357-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					358-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					360-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					363-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					365-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					366-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					373-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					375-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					380-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					383-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					389-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					392-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					397-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					398-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					399-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					401-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					402-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					403-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					404-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					405-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					407-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
					410-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]'


			3dttest++ -prefix d_vs_v-${h}-connect+tlrc \
						-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
						-paired \
						-setA \
								193-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								203-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								206-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								211-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								212-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								216-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								217-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								218-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								225-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								229-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								237-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								238-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								240-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								242-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								244-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								247-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								248-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								250-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								253-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								254-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								257-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								259-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								263-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								268-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								273-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								280-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								282-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								285-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								287-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								289-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								290-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								291-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								293-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								294-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								295-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								296-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								297-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								299-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								300-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								301-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								302-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								306-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								307-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								309-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								310-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								311-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								313-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								315-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								316-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								317-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								319-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								321-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								323-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								324-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								326-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								328-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								331-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								332-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								336-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								337-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								339-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								341-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								343-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								344-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								345-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								346-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								348-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								350-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								351-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								352-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								354-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								357-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								358-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								360-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								363-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								365-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								366-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								373-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								375-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								380-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								383-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								389-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								392-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								397-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								398-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								399-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								401-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								402-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								403-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								404-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								405-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								407-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
								410-insula_${h}-bucket_z_REML+tlrc.BRIK'[1]' \
						-setB \
								193-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								203-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								206-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								211-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								212-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								216-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								217-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								218-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								225-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								229-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								237-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								238-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								240-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								242-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								244-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								247-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								248-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								250-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								253-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								254-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								257-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								259-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								263-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								268-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								273-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								280-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								282-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								285-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								287-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								289-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								290-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								291-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								293-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								294-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								295-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								296-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								297-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								299-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								300-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								301-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								302-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								306-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								307-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								309-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								310-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								311-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								313-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								315-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								316-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								317-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								319-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								321-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								323-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								324-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								326-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								328-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								331-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								332-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								336-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								337-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								339-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								341-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								343-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								344-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								345-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								346-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								348-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								350-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								351-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								352-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								354-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								357-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								358-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								360-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								363-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								365-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								366-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								373-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								375-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								380-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								383-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								389-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								392-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								397-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								398-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								399-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								401-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								402-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								403-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								404-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								405-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								407-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
								410-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]'


						3dttest++ -prefix p_vs_v-${h}-connect+tlrc \
											-mask /Users/jflanner/Documents/RESTING/group_mask/${mask}+tlrc \
											-paired \
											-setA \
											193-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											203-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											206-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											211-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											212-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											216-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											217-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											218-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											225-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											229-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											237-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											238-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											240-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											242-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											244-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											247-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											248-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											250-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											253-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											254-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											257-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											259-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											263-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											268-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											273-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											280-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											282-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											285-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											287-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											289-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											290-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											291-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											293-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											294-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											295-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											296-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											297-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											299-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											300-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											301-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											302-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											306-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											307-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											309-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											310-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											311-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											313-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											315-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											316-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											317-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											319-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											321-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											323-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											324-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											326-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											328-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											331-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											332-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											336-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											337-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											339-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											341-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											343-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											344-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											345-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											346-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											348-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											350-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											351-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											352-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											354-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											357-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											358-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											360-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											363-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											365-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											366-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											373-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											375-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											380-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											383-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											389-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											392-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											397-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											398-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											399-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											401-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											402-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											403-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											404-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											405-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											407-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											410-insula_${h}-bucket_z_REML+tlrc.BRIK'[4]' \
											-setB \
													193-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													203-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													206-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													211-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													212-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													216-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													217-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													218-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													225-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													229-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													237-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													238-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													240-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													242-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													244-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													247-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													248-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													250-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													253-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													254-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													257-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													259-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													263-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													268-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													273-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													280-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													282-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													285-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													287-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													289-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													290-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													291-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													293-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													294-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													295-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													296-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													297-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													299-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													300-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													301-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													302-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													306-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													307-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													309-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													310-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													311-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													313-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													315-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													316-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													317-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													319-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													321-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													323-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													324-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													326-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													328-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													331-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													332-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													336-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													337-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													339-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													341-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													343-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													344-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													345-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													346-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													348-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													350-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													351-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													352-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													354-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													357-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													358-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													360-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													363-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													365-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													366-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													373-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													375-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													380-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													383-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													389-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													392-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													397-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													398-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													399-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													401-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													402-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													403-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													404-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													405-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													407-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]' \
													410-insula_${h}-bucket_z_REML+tlrc.BRIK'[7]'

		done
done

echo "END Ttest"
