
#s4 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-203/func/sub-203-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s31 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-285/func/sub-285-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s88 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-297/func/sub-297-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s37 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-318/func/sub-318-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s97 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-326/func/sub-326-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s69 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-328/func/sub-328-eat_inhib.nii.gz_REML+tlrc'[5]' \
#s77 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-383/func/sub-383-eat_inhib.nii.gz_REML+tlrc'[5]' \

3dttest++ -mask /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/HIVCB_GroupMask+tlrc \
-prefix inhib-all-ttest_error \
-clustsim \
-setA allsample \
s1 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-193/func/sub-193-eat_inhib.nii.gz_REML+tlrc'[5]' \
s2 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-194/func/sub-194-eat_inhib.nii.gz_REML+tlrc'[5]' \
s3 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-198/func/sub-198-eat_inhib.nii.gz_REML+tlrc'[5]' \
s4 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-398/func/sub-398-eat_inhib.nii.gz_REML+tlrc'[5]' \
s5 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-217/func/sub-217-eat_inhib.nii.gz_REML+tlrc'[5]' \
s6 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-283/func/sub-283-eat_inhib.nii.gz_REML+tlrc'[5]' \
s7 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-289/func/sub-289-eat_inhib.nii.gz_REML+tlrc'[5]' \
s8 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-293/func/sub-293-eat_inhib.nii.gz_REML+tlrc'[5]' \
s9 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-294/func/sub-294-eat_inhib.nii.gz_REML+tlrc'[5]' \
s10 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-317/func/sub-317-eat_inhib.nii.gz_REML+tlrc'[5]' \
s11 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-339/func/sub-339-eat_inhib.nii.gz_REML+tlrc'[5]' \
s12 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-342/func/sub-342-eat_inhib.nii.gz_REML+tlrc'[5]' \
s13 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-352/func/sub-352-eat_inhib.nii.gz_REML+tlrc'[5]' \
s14 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-354/func/sub-354-eat_inhib.nii.gz_REML+tlrc'[5]' \
s15 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-357/func/sub-357-eat_inhib.nii.gz_REML+tlrc'[5]' \
s16 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-378/func/sub-378-eat_inhib.nii.gz_REML+tlrc'[5]' \
s17 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-387/func/sub-387-eat_inhib.nii.gz_REML+tlrc'[5]' \
s18 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-388/func/sub-388-eat_inhib.nii.gz_REML+tlrc'[5]' \
s19 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-399/func/sub-399-eat_inhib.nii.gz_REML+tlrc'[5]' \
s20 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-401/func/sub-401-eat_inhib.nii.gz_REML+tlrc'[5]' \
s21 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-402/func/sub-402-eat_inhib.nii.gz_REML+tlrc'[5]' \
s22 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-403/func/sub-403-eat_inhib.nii.gz_REML+tlrc'[5]' \
s23 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-404/func/sub-404-eat_inhib.nii.gz_REML+tlrc'[5]' \
s24 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-350/func/sub-350-eat_inhib.nii.gz_REML+tlrc'[5]' \
s25 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-212/func/sub-212-eat_inhib.nii.gz_REML+tlrc'[5]' \
s26 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-218/func/sub-218-eat_inhib.nii.gz_REML+tlrc'[5]' \
s27 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-240/func/sub-240-eat_inhib.nii.gz_REML+tlrc'[5]' \
s28 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-250/func/sub-250-eat_inhib.nii.gz_REML+tlrc'[5]' \
s29 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-254/func/sub-254-eat_inhib.nii.gz_REML+tlrc'[5]' \
s30 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-266/func/sub-266-eat_inhib.nii.gz_REML+tlrc'[5]' \
s32 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-287/func/sub-287-eat_inhib.nii.gz_REML+tlrc'[5]' \
s33 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-290/func/sub-290-eat_inhib.nii.gz_REML+tlrc'[5]' \
s34 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-291/func/sub-291-eat_inhib.nii.gz_REML+tlrc'[5]' \
s35 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-295/func/sub-295-eat_inhib.nii.gz_REML+tlrc'[5]' \
s36 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-307/func/sub-307-eat_inhib.nii.gz_REML+tlrc'[5]' \
s38 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-319/func/sub-319-eat_inhib.nii.gz_REML+tlrc'[5]' \
s39 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-321/func/sub-321-eat_inhib.nii.gz_REML+tlrc'[5]' \
s40 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-409/func/sub-409-eat_inhib.nii.gz_REML+tlrc'[5]' \
s41 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-323/func/sub-323-eat_inhib.nii.gz_REML+tlrc'[5]' \
s42 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-333/func/sub-333-eat_inhib.nii.gz_REML+tlrc'[5]' \
s43 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-334/func/sub-334-eat_inhib.nii.gz_REML+tlrc'[5]' \
s44 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-336/func/sub-336-eat_inhib.nii.gz_REML+tlrc'[5]' \
s45 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-337/func/sub-337-eat_inhib.nii.gz_REML+tlrc'[5]' \
s46 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-340/func/sub-340-eat_inhib.nii.gz_REML+tlrc'[5]' \
s47 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-378/func/sub-378-eat_inhib.nii.gz_REML+tlrc'[5]' \
s48 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-405/func/sub-405-eat_inhib.nii.gz_REML+tlrc'[5]' \
s49 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-407/func/sub-407-eat_inhib.nii.gz_REML+tlrc'[5]' \
s50 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-410/func/sub-410-eat_inhib.nii.gz_REML+tlrc'[5]' \
s51 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-380/func/sub-380-eat_inhib.nii.gz_REML+tlrc'[5]' \
s52 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-211/func/sub-211-eat_inhib.nii.gz_REML+tlrc'[5]' \
s53 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-216/func/sub-216-eat_inhib.nii.gz_REML+tlrc'[5]' \
s54 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-237/func/sub-237-eat_inhib.nii.gz_REML+tlrc'[5]' \
s55 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-238/func/sub-238-eat_inhib.nii.gz_REML+tlrc'[5]' \
s56 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-242/func/sub-242-eat_inhib.nii.gz_REML+tlrc'[5]' \
s57 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-244/func/sub-244-eat_inhib.nii.gz_REML+tlrc'[5]' \
s58 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-247/func/sub-247-eat_inhib.nii.gz_REML+tlrc'[5]' \
s59 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-248/func/sub-248-eat_inhib.nii.gz_REML+tlrc'[5]' \
s60 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-253/func/sub-253-eat_inhib.nii.gz_REML+tlrc'[5]' \
s61 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-263/func/sub-263-eat_inhib.nii.gz_REML+tlrc'[5]' \
s62 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-280/func/sub-280-eat_inhib.nii.gz_REML+tlrc'[5]' \
s63 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-299/func/sub-299-eat_inhib.nii.gz_REML+tlrc'[5]' \
s64 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-301/func/sub-301-eat_inhib.nii.gz_REML+tlrc'[5]' \
s65 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-306/func/sub-306-eat_inhib.nii.gz_REML+tlrc'[5]' \
s66 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-311/func/sub-311-eat_inhib.nii.gz_REML+tlrc'[5]' \
s67 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-313/func/sub-313-eat_inhib.nii.gz_REML+tlrc'[5]' \
s68 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-314/func/sub-314-eat_inhib.nii.gz_REML+tlrc'[5]' \
s70 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-341/func/sub-341-eat_inhib.nii.gz_REML+tlrc'[5]' \
s71 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-343/func/sub-343-eat_inhib.nii.gz_REML+tlrc'[5]' \
s72 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-351/func/sub-351-eat_inhib.nii.gz_REML+tlrc'[5]' \
s73 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-358/func/sub-358-eat_inhib.nii.gz_REML+tlrc'[5]' \
s74 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-365/func/sub-365-eat_inhib.nii.gz_REML+tlrc'[5]' \
s75 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-370/func/sub-370-eat_inhib.nii.gz_REML+tlrc'[5]' \
s76 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-373/func/sub-373-eat_inhib.nii.gz_REML+tlrc'[5]' \
s78 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-389/func/sub-389-eat_inhib.nii.gz_REML+tlrc'[5]' \
s79 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-206/func/sub-206-eat_inhib.nii.gz_REML+tlrc'[5]' \
s80 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-225/func/sub-225-eat_inhib.nii.gz_REML+tlrc'[5]' \
s81 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-229/func/sub-229-eat_inhib.nii.gz_REML+tlrc'[5]' \
s82 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-257/func/sub-257-eat_inhib.nii.gz_REML+tlrc'[5]' \
s83 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-258/func/sub-258-eat_inhib.nii.gz_REML+tlrc'[5]' \
s84 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-259/func/sub-259-eat_inhib.nii.gz_REML+tlrc'[5]' \
s85 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-268/func/sub-268-eat_inhib.nii.gz_REML+tlrc'[5]' \
s86 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-273/func/sub-273-eat_inhib.nii.gz_REML+tlrc'[5]' \
s87 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-279/func/sub-279-eat_inhib.nii.gz_REML+tlrc'[5]' \
s89 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-282/func/sub-282-eat_inhib.nii.gz_REML+tlrc'[5]' \
s90 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-300/func/sub-300-eat_inhib.nii.gz_REML+tlrc'[5]' \
s91 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-302/func/sub-302-eat_inhib.nii.gz_REML+tlrc'[5]' \
s92 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-309/func/sub-309-eat_inhib.nii.gz_REML+tlrc'[5]' \
s93 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-310/func/sub-310-eat_inhib.nii.gz_REML+tlrc'[5]' \
s94 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-316/func/sub-316-eat_inhib.nii.gz_REML+tlrc'[5]' \
s95 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-320/func/sub-320-eat_inhib.nii.gz_REML+tlrc'[5]' \
s96 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-324/func/sub-324-eat_inhib.nii.gz_REML+tlrc'[5]' \
s98 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-331/func/sub-331-eat_inhib.nii.gz_REML+tlrc'[5]' \
s99 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-332/func/sub-332-eat_inhib.nii.gz_REML+tlrc'[5]' \
s100 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-344/func/sub-344-eat_inhib.nii.gz_REML+tlrc'[5]' \
s101 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-345/func/sub-345-eat_inhib.nii.gz_REML+tlrc'[5]' \
s102 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-346/func/sub-346-eat_inhib.nii.gz_REML+tlrc'[5]' \
s103 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-348/func/sub-348-eat_inhib.nii.gz_REML+tlrc'[5]' \
s104 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-360/func/sub-360-eat_inhib.nii.gz_REML+tlrc'[5]' \
s105 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-363/func/sub-363-eat_inhib.nii.gz_REML+tlrc'[5]' \
s106 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-366/func/sub-366-eat_inhib.nii.gz_REML+tlrc'[5]' \
s107 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-375/func/sub-375-eat_inhib.nii.gz_REML+tlrc'[5]' \
s108 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-392/func/sub-392-eat_inhib.nii.gz_REML+tlrc'[5]' \
s109 /home/data/nbc/Sutherland_HIVCB/derivatives/afni-processing/preprocessed-data/sub-397/func/sub-397-eat_aware.nii.gz_REML+tlrc'[5]'
